# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-json
          - id: check-toml
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.10
      hooks:
          - name: lint benchmark
            id: ruff-check
            args: ["--fix"]
            files: ^benchmark/
          - name: lint baselines
            id: ruff-check
            args: ["--fix"]
            files: ^baselines/
          - name: code format benchmark
            id: ruff-format
            files: ^benchmark/
          - name: code format baselines
            id: ruff-format
            files: ^baselines/
